#############################################################################
# Makefile for building: qcadqcad
# Generated by qmake (3.1) (Qt 5.13.0)
# Project:  qcad.pro
# Template: subdirs
# Command: D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\bin\qmake.exe -o Makefile qcad.pro "CONFIG+=ractivated"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-src \
		sub----build-qcad-librecad-Debug \
		sub----build-qcad-qcad-Debug \
		sub----build-qcad-unknown-Debug \
		sub-support


sub-src-qmake_all:  FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f Makefile qmake_all
sub-src: $(MAKEFILE) FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile
sub-src-make_first-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile 
sub-src-make_first: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile 
sub-src-all-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile all
sub-src-all: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile all
sub-src-clean-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile clean
sub-src-clean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile clean
sub-src-distclean-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile distclean
sub-src-distclean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile install
sub-src-install_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile uninstall
sub-src-uninstall_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile uninstall
sub----build-qcad-librecad-Debug-qmake_all: sub-src-qmake_all FORCE
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	cd ..\build-qcad-librecad-Debug\ && $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && $(MAKE) -f Makefile qmake_all
sub----build-qcad-librecad-Debug: $(MAKEFILE) FORCE
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile
sub----build-qcad-librecad-Debug-make_first-ordered: sub-src-make_first-ordered  FORCE
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile 
sub----build-qcad-librecad-Debug-make_first: FORCE
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile 
sub----build-qcad-librecad-Debug-all-ordered: sub-src-all-ordered  FORCE
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile all
sub----build-qcad-librecad-Debug-all: FORCE
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile all
sub----build-qcad-librecad-Debug-clean-ordered: sub-src-clean-ordered  FORCE
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile clean
sub----build-qcad-librecad-Debug-clean: FORCE
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile clean
sub----build-qcad-librecad-Debug-distclean-ordered: sub-src-distclean-ordered  FORCE
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile distclean
sub----build-qcad-librecad-Debug-distclean: FORCE
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile distclean
sub----build-qcad-librecad-Debug-install_subtargets-ordered: sub-src-install_subtargets-ordered  FORCE
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile install
sub----build-qcad-librecad-Debug-install_subtargets: FORCE
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile install
sub----build-qcad-librecad-Debug-uninstall_subtargets-ordered: sub-src-uninstall_subtargets-ordered  FORCE
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile uninstall
sub----build-qcad-librecad-Debug-uninstall_subtargets: FORCE
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile uninstall
sub----build-qcad-qcad-Debug-qmake_all: sub----build-qcad-librecad-Debug-qmake_all FORCE
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	cd ..\build-qcad-qcad-Debug\ && $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && $(MAKE) -f Makefile qmake_all
sub----build-qcad-qcad-Debug: $(MAKEFILE) FORCE
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile
sub----build-qcad-qcad-Debug-make_first-ordered: sub----build-qcad-librecad-Debug-make_first-ordered  FORCE
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile 
sub----build-qcad-qcad-Debug-make_first: FORCE
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile 
sub----build-qcad-qcad-Debug-all-ordered: sub----build-qcad-librecad-Debug-all-ordered  FORCE
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile all
sub----build-qcad-qcad-Debug-all: FORCE
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile all
sub----build-qcad-qcad-Debug-clean-ordered: sub----build-qcad-librecad-Debug-clean-ordered  FORCE
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile clean
sub----build-qcad-qcad-Debug-clean: FORCE
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile clean
sub----build-qcad-qcad-Debug-distclean-ordered: sub----build-qcad-librecad-Debug-distclean-ordered  FORCE
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile distclean
sub----build-qcad-qcad-Debug-distclean: FORCE
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile distclean
sub----build-qcad-qcad-Debug-install_subtargets-ordered: sub----build-qcad-librecad-Debug-install_subtargets-ordered  FORCE
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile install
sub----build-qcad-qcad-Debug-install_subtargets: FORCE
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile install
sub----build-qcad-qcad-Debug-uninstall_subtargets-ordered: sub----build-qcad-librecad-Debug-uninstall_subtargets-ordered  FORCE
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile uninstall
sub----build-qcad-qcad-Debug-uninstall_subtargets: FORCE
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile uninstall
sub----build-qcad-unknown-Debug-qmake_all: sub----build-qcad-qcad-Debug-qmake_all FORCE
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	cd ..\build-qcad-unknown-Debug\ && $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && $(MAKE) -f Makefile qmake_all
sub----build-qcad-unknown-Debug: $(MAKEFILE) FORCE
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile
sub----build-qcad-unknown-Debug-make_first-ordered: sub----build-qcad-qcad-Debug-make_first-ordered  FORCE
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile 
sub----build-qcad-unknown-Debug-make_first: FORCE
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile 
sub----build-qcad-unknown-Debug-all-ordered: sub----build-qcad-qcad-Debug-all-ordered  FORCE
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile all
sub----build-qcad-unknown-Debug-all: FORCE
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile all
sub----build-qcad-unknown-Debug-clean-ordered: sub----build-qcad-qcad-Debug-clean-ordered  FORCE
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile clean
sub----build-qcad-unknown-Debug-clean: FORCE
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile clean
sub----build-qcad-unknown-Debug-distclean-ordered: sub----build-qcad-qcad-Debug-distclean-ordered  FORCE
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile distclean
sub----build-qcad-unknown-Debug-distclean: FORCE
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile distclean
sub----build-qcad-unknown-Debug-install_subtargets-ordered: sub----build-qcad-qcad-Debug-install_subtargets-ordered  FORCE
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile install
sub----build-qcad-unknown-Debug-install_subtargets: FORCE
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile install
sub----build-qcad-unknown-Debug-uninstall_subtargets-ordered: sub----build-qcad-qcad-Debug-uninstall_subtargets-ordered  FORCE
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile uninstall
sub----build-qcad-unknown-Debug-uninstall_subtargets: FORCE
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile uninstall
sub-support-qmake_all: sub----build-qcad-unknown-Debug-qmake_all FORCE
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	cd support\ && $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && $(MAKE) -f Makefile qmake_all
sub-support: $(MAKEFILE) FORCE
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile
sub-support-make_first-ordered: sub----build-qcad-unknown-Debug-make_first-ordered  FORCE
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile 
sub-support-make_first: FORCE
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile 
sub-support-all-ordered: sub----build-qcad-unknown-Debug-all-ordered  FORCE
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile all
sub-support-all: FORCE
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile all
sub-support-clean-ordered: sub----build-qcad-unknown-Debug-clean-ordered  FORCE
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile clean
sub-support-clean: FORCE
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile clean
sub-support-distclean-ordered: sub----build-qcad-unknown-Debug-distclean-ordered  FORCE
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile distclean
sub-support-distclean: FORCE
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile distclean
sub-support-install_subtargets-ordered: sub----build-qcad-unknown-Debug-install_subtargets-ordered  FORCE
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile install
sub-support-install_subtargets: FORCE
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile install
sub-support-uninstall_subtargets-ordered: sub----build-qcad-unknown-Debug-uninstall_subtargets-ordered  FORCE
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile uninstall
sub-support-uninstall_subtargets: FORCE
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile uninstall

Makefile: qcad.pro .qmake.cache D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\win32-msvc\qmake.conf D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\spec_pre.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\common\angle.conf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\common\windows-desktop.conf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\common\windows-vulkan.conf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\common\msvc-desktop.conf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\qconfig.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_core.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_designer.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_edid_support_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_gui.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_help.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_location.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_network.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_positioningquick.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_qml.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quick.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_repparser.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_repparser_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_script.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_script_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_scripttools.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_sql.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_svg.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_texttospeech.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webengine.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webengine_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webenginecore.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webview.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_xml.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\qt_functions.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\qt_config.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\win32-msvc\qmake.conf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\spec_post.prf \
		.qmake.cache \
		.qmake.stash \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\exclusive_builds.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\common\msvc-version.conf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\toolchain.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\default_pre.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\win32\default_pre.prf \
		shared.pri \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\resolve_config.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\exclusive_builds_post.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\default_post.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\warn_on.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\precompile_header.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\qmake_use.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\file_copies.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\win32\windows.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\testcase_targets.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\exceptions.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\yacc.prf \
		D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\lex.prf \
		qcad.pro
	$(QMAKE) -o Makefile qcad.pro "CONFIG+=ractivated"
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\spec_pre.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\common\angle.conf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\common\windows-desktop.conf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\common\windows-vulkan.conf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\common\msvc-desktop.conf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\qconfig.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_core.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_designer.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_edid_support_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_gui.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_help.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_location.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_network.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_positioningquick.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_qml.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quick.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_repparser.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_repparser_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_script.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_script_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_scripttools.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_scripttools_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_sql.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_svg.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_texttospeech.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_vulkan_support_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webengine.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webengine_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webenginecore.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webview.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_xml.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\qt_functions.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\qt_config.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\win32-msvc\qmake.conf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\spec_post.prf:
.qmake.cache:
.qmake.stash:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\exclusive_builds.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\common\msvc-version.conf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\toolchain.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\default_pre.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\win32\default_pre.prf:
shared.pri:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\resolve_config.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\exclusive_builds_post.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\default_post.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\warn_on.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\precompile_header.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\qmake_use.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\file_copies.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\win32\windows.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\testcase_targets.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\exceptions.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\yacc.prf:
D:\Qt\Qt5.13.0-2\5.13.0\msvc2017_64\mkspecs\features\lex.prf:
qcad.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile qcad.pro "CONFIG+=ractivated"

qmake_all: sub-src-qmake_all sub----build-qcad-librecad-Debug-qmake_all sub----build-qcad-qcad-Debug-qmake_all sub----build-qcad-unknown-Debug-qmake_all sub-support-qmake_all FORCE

make_first: sub-src-make_first-ordered sub----build-qcad-librecad-Debug-make_first-ordered sub----build-qcad-qcad-Debug-make_first-ordered sub----build-qcad-unknown-Debug-make_first-ordered sub-support-make_first-ordered  FORCE
all: sub-src-all-ordered sub----build-qcad-librecad-Debug-all-ordered sub----build-qcad-qcad-Debug-all-ordered sub----build-qcad-unknown-Debug-all-ordered sub-support-all-ordered  FORCE
clean: sub-src-clean-ordered sub----build-qcad-librecad-Debug-clean-ordered sub----build-qcad-qcad-Debug-clean-ordered sub----build-qcad-unknown-Debug-clean-ordered sub-support-clean-ordered  FORCE
distclean: sub-src-distclean-ordered sub----build-qcad-librecad-Debug-distclean-ordered sub----build-qcad-qcad-Debug-distclean-ordered sub----build-qcad-unknown-Debug-distclean-ordered sub-support-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-src-install_subtargets-ordered sub----build-qcad-librecad-Debug-install_subtargets-ordered sub----build-qcad-qcad-Debug-install_subtargets-ordered sub----build-qcad-unknown-Debug-install_subtargets-ordered sub-support-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-uninstall_subtargets-ordered sub----build-qcad-librecad-Debug-uninstall_subtargets-ordered sub----build-qcad-qcad-Debug-uninstall_subtargets-ordered sub----build-qcad-unknown-Debug-uninstall_subtargets-ordered sub-support-uninstall_subtargets-ordered FORCE

sub-src-debug_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile debug
sub----build-qcad-librecad-Debug-debug_ordered: sub-src-debug_ordered 
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile debug
sub----build-qcad-qcad-Debug-debug_ordered: sub----build-qcad-librecad-Debug-debug_ordered 
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile debug
sub----build-qcad-unknown-Debug-debug_ordered: sub----build-qcad-qcad-Debug-debug_ordered 
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile debug
sub-support-debug_ordered: sub----build-qcad-unknown-Debug-debug_ordered 
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile debug
debug: sub-src-debug_ordered sub----build-qcad-librecad-Debug-debug_ordered sub----build-qcad-qcad-Debug-debug_ordered sub----build-qcad-unknown-Debug-debug_ordered sub-support-debug_ordered

sub-src-release_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile release
sub----build-qcad-librecad-Debug-release_ordered: sub-src-release_ordered 
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile release
sub----build-qcad-qcad-Debug-release_ordered: sub----build-qcad-librecad-Debug-release_ordered 
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile release
sub----build-qcad-unknown-Debug-release_ordered: sub----build-qcad-qcad-Debug-release_ordered 
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile release
sub-support-release_ordered: sub----build-qcad-unknown-Debug-release_ordered 
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile release
release: sub-src-release_ordered sub----build-qcad-librecad-Debug-release_ordered sub----build-qcad-qcad-Debug-release_ordered sub----build-qcad-unknown-Debug-release_ordered sub-support-release_ordered

sub-src-check_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile check
sub----build-qcad-librecad-Debug-check_ordered: sub-src-check_ordered 
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile check
sub----build-qcad-qcad-Debug-check_ordered: sub----build-qcad-librecad-Debug-check_ordered 
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile check
sub----build-qcad-unknown-Debug-check_ordered: sub----build-qcad-qcad-Debug-check_ordered 
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile check
sub-support-check_ordered: sub----build-qcad-unknown-Debug-check_ordered 
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile check
check: sub-src-check_ordered sub----build-qcad-librecad-Debug-check_ordered sub----build-qcad-qcad-Debug-check_ordered sub----build-qcad-unknown-Debug-check_ordered sub-support-check_ordered

sub-src-benchmark_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\src\src.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile benchmark
sub----build-qcad-librecad-Debug-benchmark_ordered: sub-src-benchmark_ordered 
	@if not exist ..\build-qcad-librecad-Debug\ mkdir ..\build-qcad-librecad-Debug\ & if not exist ..\build-qcad-librecad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-librecad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-librecad-Debug\build-qcad-librecad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile benchmark
sub----build-qcad-qcad-Debug-benchmark_ordered: sub----build-qcad-librecad-Debug-benchmark_ordered 
	@if not exist ..\build-qcad-qcad-Debug\ mkdir ..\build-qcad-qcad-Debug\ & if not exist ..\build-qcad-qcad-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-qcad-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-qcad-Debug\build-qcad-qcad-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile benchmark
sub----build-qcad-unknown-Debug-benchmark_ordered: sub----build-qcad-qcad-Debug-benchmark_ordered 
	@if not exist ..\build-qcad-unknown-Debug\ mkdir ..\build-qcad-unknown-Debug\ & if not exist ..\build-qcad-unknown-Debug\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ..\build-qcad-unknown-Debug\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\build-qcad-unknown-Debug\build-qcad-unknown-Debug.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile benchmark
sub-support-benchmark_ordered: sub----build-qcad-unknown-Debug-benchmark_ordered 
	@if not exist support\ mkdir support\ & if not exist support\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd support\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\mywork\lib2\qcad\support\support.pro "CONFIG+=ractivated" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-src-benchmark_ordered sub----build-qcad-librecad-Debug-benchmark_ordered sub----build-qcad-qcad-Debug-benchmark_ordered sub----build-qcad-unknown-Debug-benchmark_ordered sub-support-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

